In [1]:
import numpy as np
import numpy.char as char

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
arr=np.ones((4,4))
np.pad(arr,pad_width=1,mode='constant',constant_values=0) # padding meaning pattern form.

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [2]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
array=np.zeros((5,5),dtype=int)
value=[1,2,3,4]
for i in range(1,5):
    array[i,i-1]=value[i-1]

    

In [12]:
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
def create_chessboard(n):
    checkboard=np.zeros((n,n),dtype=int)
    checkboard[1::2,::2]=1
    checkboard[::2,1::2]=1
    return checkboard
checkboard=create_chessboard(8)
checkboard
    
    
    

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [10]:

print(np.unravel_index(99,(6,7,8))) #the first dimension has 6 elements, second dimension has 8 elemts, the third dimension has 8 elements .
                                    # the unrevel is used to flatten the 3D to a 1D  hence the outcome is 6*7*8.


(np.int64(1), np.int64(5), np.int64(3))


np.int64(1) the first insex is 1 stored in 64 bit-integer, second index is 5-stored in 64 bit_integer,the third index is 3- stored in 64 bit_integer

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
pattern = np.array([[0, 1],[1, 0]])

checkerboard = np.tile(pattern, (4, 4))

checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
z

array([[0.18947032, 0.06773165, 0.845502  , 0.53914791, 0.00912399],
       [0.35391188, 0.78431333, 0.09155141, 0.64825285, 0.25507114],
       [0.99263336, 0.60837948, 0.16310022, 0.79280471, 0.66634019],
       [1.        , 0.89350122, 0.14979742, 0.3705161 , 0.59728196],
       [0.        , 0.02289005, 0.26336531, 0.11889701, 0.4825406 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [13]:
colour= np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),# using one since each componect has a single byte
                 ('b', np.ubyte,1),
                 ('a',np.ubyte,1)])
colour

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [36]:
matrix_5x3 = np.random.rand(5, 3)

matrix_3x2 = np.random.rand(3, 2)

result_matrix = np.dot(matrix_5x3, matrix_3x2)
result_matrix

array([[1.09092009, 0.78257327],
       [0.63773386, 0.60390627],
       [0.70814527, 0.40866308],
       [0.41193058, 0.27072628],
       [1.20257497, 0.8668933 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [15]:
arr=np.arange(11)
arr[(3< arr )&(arr<=8)] *=-1
arr



array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:

[Z**Z
2<< Z>> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z]

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\GASTO\AppData\Local\Temp\ipykernel_14420\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\GASTO\AppData\Local\Temp\ipykernel_14420\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\GASTO\AppData\Local\Temp\ipykernel_14420\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 30. How to find common values between two arrays? (★☆☆)

In [16]:
X1 =np.random.randint(0,10,10)
X2=np.random.randint(0,10,10)
np.intersect1d(X1,X2)

array([1, 4, 9], dtype=int32)