# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version and the configuration (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
def function6():
    arr=np.zeros(10,dtype=int)
    return arr

In [4]:
function6()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [49]:
np.size(function6())

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [51]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
def function6():
    array=np.zeros(10,dtype=int)
    array[4]=1
    return array
    

In [8]:
function6()

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
arr=np.arange(10,50,dtype=int)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
y=np.arange(0,9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [53]:
np.argsort([1,2,0,0,4,0])# finds the indices of all elements

array([2, 3, 5, 0, 1, 4])

In [58]:
array = [1, 2, 0, 0, 4, 0]


non_zero_indices = [i for i, x in enumerate (array) if x != 0]
non_zero_indices

[0, 1, 4]

#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
y=np.eye((3),dtype=int)
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
n=np.random.rand(3,3,3)
n

array([[[0.43845541, 0.50017533, 0.74827566],
        [0.73632144, 0.25463688, 0.85845068],
        [0.32914321, 0.2315912 , 0.22910192]],

       [[0.55036369, 0.3555769 , 0.83657175],
        [0.405389  , 0.37889047, 0.97061719],
        [0.39528258, 0.02002756, 0.47373492]],

       [[0.66687161, 0.65752387, 0.19888987],
        [0.25966639, 0.6235188 , 0.25397323],
        [0.39545757, 0.09852786, 0.12989216]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
arr=np.random.randint(100,size=(10,10))
arr

array([[78, 53, 69, 56, 82, 22, 43, 68, 51, 36],
       [ 8, 65, 74, 25, 72, 95, 80, 76, 96, 65],
       [49, 92, 34, 89, 33, 22,  8, 55, 47, 90],
       [92, 73,  5, 45, 27, 18, 33, 79, 52, 18],
       [26,  6,  5, 34, 15, 35, 81, 16, 69, 40],
       [40,  1, 19, 51,  9, 68,  8, 23, 30, 19],
       [10, 66,  8, 12,  0, 87, 53, 29, 53, 14],
       [94, 53, 88, 99, 42, 13, 36, 40, 91, 58],
       [79, 61, 82, 28, 10, 40,  3,  4, 67, 73],
       [73, 94, 14,  3, 98,  4, 42, 95, 48, 41]], dtype=int32)

In [30]:
print(np.min(arr))
print(np.max(arr))

0
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
arr=np.random.rand(30)
arr

array([0.21896939, 0.51383942, 0.49765419, 0.76801413, 0.85845043,
       0.99068804, 0.80248222, 0.76911146, 0.16117443, 0.86723119,
       0.03867214, 0.33971098, 0.49342968, 0.00119738, 0.68225365,
       0.48495225, 0.59500663, 0.12678055, 0.07363105, 0.07446191,
       0.50972496, 0.96228091, 0.32967787, 0.82320573, 0.24354043,
       0.20873134, 0.44367024, 0.49811976, 0.25471346, 0.41770565])

In [39]:
print(np.mean(arr))

0.46830271641145466


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
n=np.ones((4,4))
n[1:-1,1:-1]=0
n

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])