# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [4]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')# rep todays date with day precision while (1,'D')time delta of one day by subtraction it results to yesterday 
print('yesterday:',yesterday)
today=np.datetime64('today','D')
print('today:',today)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')# rep todays date with day precision while (1,'D') time delta of one day by addition it results totomorrow.
print('tomorrow:',tomorrow)

yesterday: 2024-07-16
today: 2024-07-17
tomorrow: 2024-07-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [5]:
print("july,2016")
np.arange('2016-07','2016-08',dtype='datetime64[D]')

july,2016


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [6]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
x=np.random.uniform(0,10,10)
floored_x=np.floor(x)
ceiled_x=np.ceil(x)
truncated_x=np.trunc(x)
print(x)
print(floored_x)#smallest
print(ceiled_x)#largest
print(truncated_x)

[2.04184429 4.22353719 4.16367769 9.58013266 6.35162088 3.74499966
 9.0310822  1.60060023 4.73545896 0.57047139]
[2. 4. 4. 9. 6. 3. 9. 1. 4. 0.]
[ 3.  5.  5. 10.  7.  4. 10.  2.  5.  1.]
[2. 4. 4. 9. 6. 3. 9. 1. 4. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
matrix=np.zeros((5,5))
matrix+=np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
def generate_integers():
    for i in range(10):
        yield i


integer_list = list(generate_integers())


integer_array = np.array(integer_list)


print(integer_array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
vector = np.linspace(0, 1, 12)[1:-1]

vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
random_vector = np.random.rand(10)  # Generates 10 random values between 0 and 1


sorted_vector = np.sort(random_vector)

print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)

Random Vector: [0.12668782 0.66519113 0.48753135 0.85514814 0.34118761 0.87238973
 0.69021867 0.14850322 0.53666511 0.48027885]
Sorted Vector: [0.12668782 0.14850322 0.34118761 0.48027885 0.48753135 0.53666511
 0.66519113 0.69021867 0.85514814 0.87238973]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
x=np.arange(10)
np.add.reduce(x)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [17]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)


are_equal = np.array_equal(A, B)
are_equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
y=np.zeros(10)
y.flags.writeable=False



#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [15]:
cartesian_coordinates = np.random.rand(10, 2)

r = np.sqrt(cartesian_coordinates[:, 0]**2 + cartesian_coordinates[:, 1]**2)
theta = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])
polar_coordinates = np.column_stack((r, theta))
polar_coordinates

array([[1.34396993, 0.78810175],
       [0.67278752, 0.3975226 ],
       [0.26529219, 0.28249004],
       [0.45422941, 1.27603823],
       [0.92045061, 1.06706512],
       [0.93465657, 0.62079924],
       [1.24726217, 0.90758861],
       [0.71040806, 1.27564048],
       [0.52084425, 0.9894848 ],
       [1.26525847, 0.77924333]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [24]:
random_vector = np.random.rand(10)

print("Original vector:", random_vector)

max_index = np.argmax(random_vector)
random_vector[max_index] = 0


print("Modified vector:", random_vector)


Original vector: [0.69743426 0.66417977 0.72387514 0.04742362 0.76199944 0.71518836
 0.77878704 0.86792729 0.32193003 0.19585073]
Modified vector: [0.69743426 0.66417977 0.72387514 0.04742362 0.76199944 0.71518836
 0.77878704 0.         0.32193003 0.19585073]
